### ISSUE TITLE
Issue with Jellyfin Android App Version 0.12.1 (Released) and Roku Jellyfin App Version 1.4 Build 9 (Latest)

### ISSUE THREAD

**Issue by Georgi9999** [crobibero/Jellyfin.Channels.LazyMan#18]
The latest Jellyfin Android App has broken the plugin on the app side, as soon as I open the Lazyman App it crashed the Android TV Jellyfin App and closed the app.  From the log file it appears this is the error "The remote party closed the WebSocket connection without completing the close handshake".  All other features of the Jellyfin App are working.  This just happened with the latest release this week of the Jellyfin Android App V0.12.1, before under V0.11.5 the Lazyman plugin worked great.  I am running the latest Windows server version of Jellyfin 10.7 and the latest plugin version of Lazyman (V10.0), the plugin works on the server side.  As a FYI only, the plugin also stopped working with the latest release of the Jellyfin App for ROKU, you can get into Lazyman and choose your game, but playing the game instantly crashes the app.  Under the Jellyfin App for Android TV, simply selecting Lazyman within the App is what crashes the app.  Thank you for all your work on the Lazyman plugin, if you put out a new version and want me to test it please let me know, I'll do it right away.  Thank you again!

**Comment by crobibero** [comment]
This is not an issue with the plugin, but an issue with the respective clients. I have no issues using it in the official Android (mobile) app, or the official iOS app.

**Comment by bpoulliot** [comment]
I can open a new issue if needed, but this is crashing on the official Android Jellyfin app as well as the Roku Jellyfin app (1.4 build 9 and 1.4 build 11). Is there a root cause? I'm not using anything funky the plugin was working beautifully until a couple weeks ago. Even if no root cause, are you able to pinpoint versions you've tested on? I can provide more detail on my setup or open a new issue if needed, but this perfectly describes the behavior. On Android Jellyfin is not a complete crash of the app, but selecting a game turns the screen black as if it's retrieving data, them returns to the previous screen.

**Comment by crobibero** [comment]
Please open a new issue and include logs.
